blank_issues_enabled: false

contact_links:
  - name: ðŸ—£ GitHub Discussions
    url: https://github.com/NickvisionApps/Parabolic/discussions
    about: >
      Use Discussions for general questions, usage help, packaging issues,
      or topics that are not clearly bugs or feature requests.
      For documentation, open Parabolic and press `F1` or use the Help menu.

  - name: ðŸ’¬ Matrix Chat
    url: https://matrix.to/#/#parabolic:matrix.org
    about: >
      Chat with the community and developers in real time.
      Ideal for quick questions or troubleshooting help.
