blank_issues_enabled: false

contact_links:
  - name: ðŸ’¬ Chat on Matrix
    url: "https://matrix.to/#/#nickvision:matrix.org"
    about: "Ask usage questions and chat with developers on Matrix"

  - name: ðŸ“š Documentation
    url: "https://htmlpreview.github.io/?https://github.com/NickvisionApps/Parabolic/blob/main/docs/html/C/index.html"
    about: "Read the Parabolic docs before opening issues"
